# Generated by Django 4.2.7 on 2023-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
